### PR TITLE
Update 2019-02-02-use-ipod-nano6-lcd-for-littlevgl.md

### PR DESCRIPTION
**Pull request by techtoys**
Update 2019-8-27 for Note.

### CODE REVIEW

**Comment by techtoys** [comment]
pinout_eps32_LCD

**Comment by techtoys** [comment]
updated interface pinout diagram

**Comment by kisvegabor** [comment]
Why have you closed it?

**Comment by techtoys** [comment]
sorry, a mistake.

**Comment by kisvegabor** [comment]
Thank you!

**Pull request merged**
