### PR TITLE
Introduction to LittlevGL on Mbed-OS

### PR DESCRIPTION
**Pull request by AGlass0fMilk**
## [WIP] -- Still working on blog post before it goes live (do not merge)

Contributing blog post about[ my port of LittlevGL to Mbed-OS](https://github.com/AGlass0fMilk/mbed-lvgl) and the [uDisplay framework](https://github.com/AGlass0fMilk/uDisplay).

Gives overview of framework concepts and does an example of how to write a new display driver for Mbed-LVGL.

Not extremely beginner-friendly and the display I used isn't cheap so I'll have to do another one in the future perhaps that is easier to replicate.

To do:

- [ ] Add pictures and graphics
- [ ] Ensure step-by-step directions work out of the box
- [x] Update mbed-lvgl to lvgl 6.0
   - [x] Update lv_conf.h
   - [x] Rename `LittleVGL` class to `LittlevGL`
   - [x] Rename `LVGLDriver` to `LVGLDisplayDriver` -- there will also be input device drivers
- [x] Finish reformatting with markdown

### CODE REVIEW

**Comment by AGlass0fMilk** [comment]
I am considering breaking up this post into multiple so it is easier to digest. 

First, give an overview of uDisplay library and how to build a driver for it.

Next, actually port the driver to mbed-lvgl.

Eventually I want to make a simple "quick start" guide that is step-by-step how to set up, build, and program an mbed-lvgl application on a common dev board.

**Comment by kisvegabor** [comment]
It' looks good! I like your writing style! :slightly_smiling_face: 

> I am considering breaking up this post into multiple so it is easier to digest.

I agree it could be better to break this topic into two or more pieces because it seems every piece covers a topic independently from the others.

**Comment by AGlass0fMilk** [comment]
@kisvegabor I'd like to turn some of this content into documentation for the mbed-lvgl library. I may need some help setting up something similar to the LittlevGL site -- perhaps it could also be hosted on the LittlevGL site?

**Comment by embeddedt** [comment]
> something similar to the LittlevGL site -- perhaps it could also be hosted on the LittlevGL site?

Are you referring to https://docs.littlevgl.com?

**Comment by AGlass0fMilk** [comment]
@embeddedt Yes, that's what I mean. I haven't set up something like that before so it would take me much longer to do it without some guidance.

**Comment by embeddedt** [comment]
@AGlass0fMilk All of the stuff needed to build the documentation website is here: https://github.com/littlevgl/docs

There are instructions near the bottom about how to build it. For your purposes you can skip the Doxygen part, but you will need Sphinx. Then you can just run `./build.py` in the root folder.

**Comment by kisvegabor** [comment]
@AGlass0fMilk 
>  I'd like to turn some of this content into documentation for the mbed-lvgl library. I may need some help setting up something similar to the LittlevGL site -- perhaps it could also be hosted on the LittlevGL site?

We use the blog for porting guides and tutorials, however, I understand that a structured documentation would be more appropriate for complex things.

In the [Get started](https://docs.littlevgl.com/en/html/get-started/index.html) section we already have some porting/get started guides. What about adding your tutorials there?

@embeddedt 
We can add a FreeRTOS and C++ Guide there too. What do you think?

**Comment by embeddedt** [comment]
> We can add a FreeRTOS and C++ Guide there too. What do you think?

Good ideas!

**Comment by AGlass0fMilk** [comment]
I have finished updating my mbed-lvgl framework to LVGL 6.0! I feel better about the architecture now -- it's nice that 6.x supports multiple displays. It wasn't too hard considering how many features were added.

I have my original Noritake-Itron VFD example working again so I'll be able to start finishing the blog post drafts now.

**Comment by kisvegabor** [comment]
Good news! Thank you for the feedback!

**Comment by kisvegabor** [comment]
@AGlass0fMilk is there any news here?

**Comment by AGlass0fMilk** [comment]
@kisvegabor

I have been completely occupied by a different project at work the past couple weeks. I plan to finish the blog post this upcoming week.

**Comment by kisvegabor** [comment]
No problem, take your time!

**Pull request closed without merging**
