### PR TITLE
Micropython + LittlevGL blog post

### PR DESCRIPTION
**Pull request by amirgon**
Also added step-by-step explanation about installing Ruby and Jekyll, building and serving the blog.

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]

**Comment by kisvegabor** [comment]
@amirgon 
Looks great, thank you very much!

I've just quickly read it thought and it seems fine from my side. Is it ready to merge?

**Comment by amirgon** [comment]
> I've just quickly read it thought and it seems fine from my side. Is it ready to merge?

@kisvegabor I think it's ready to merge.
Are you planning to update littlevgl/lvgl README.md, and add micropython as an lvgl feature? If you want I can send you a PR for that.  

Once LittlevGL announces micropython availability, I think it would be a good idea to post something in Micropython forum, I think it will get some interest.
Another thing we can do is [submit a tip on Hackaday](https://hackaday.com/submit-a-tip/), or some other embedded / makers website. It might add a few additional GitHub starts to lvgl  :wink:
What do you think?

**Comment by kisvegabor** [comment]
Merged!

> Are you planning to update littlevgl/lvgl README.md, and add micropython as an lvgl feature? If you want I can send you a PR for that.

Yes, I'm planning to update the READMe and the website too to mention the Micropython support. 
So a PR to update the README would be welcome. Please do it with a similar style like the other features.

> Another thing we can do is [submit a tip on Hackaday](https://hackaday.com/submit-a-tip/), or some other embedded / makers website. It might add a few additional GitHub starts to lvgl

What a  coincidence! I've just sent a Hackaday tip this Friday. :smile:  I mentioned Micropython too! :wink:

**Comment by kisvegabor** [comment]
@amirgon 
I've read your post carefully and found three things:
1. The cover image wasn't square therefore it scaled badly. I added a [square version](https://github.com/littlevgl/blog/blob/master/assets/micropython/cover.png) of the original image.
2. The alignment in `self.symbol.align(self, lv.ALIGN.CENTER,0,0)` has no effect because the buttons have `LV_LAYOUT_CENTER` by default and it overwrites the "user align".
3. Probably it's the lack of my deep Python knowledge but I didn't understand what `lambda action,name=name: self.label.set_text('%s click' % name)` does. Maybe - similarly to me - other non-Python experts will read the post and won't understand it as well. Could you add a few lines to make it clearer?

**Comment by amirgon** [comment]
@kisvegabor 
Thank you for reviewing my post!
I will fix these issues and send you a PR.

**Comment by kisvegabor** [comment]
@amirgon 
Hackaday post: https://hackaday.com/2019/02/28/littlevgl-brings-gui-tools-to-micropython/

I wrote about LittlevGL in general but they have chosen the Micropython binding to highlight.
Congratulation!

**Comment by amirgon** [comment]
> @amirgon
> Hackaday post: https://hackaday.com/2019/02/28/littlevgl-brings-gui-tools-to-micropython/
> 
> I wrote about LittlevGL in general but they have chosen the Micropython binding to highlight.
> Congratulation!

@kisvegabor That's awesome!  
It's also very good publicity for LitttlevGL - I see it's over 1500 GitHub stars now!

**Comment by kisvegabor** [comment]
> I see it's over 1500 GitHub stars now!

Yes, we just reached the 1500 today! I've never seen so much visitors on `*.littlevgl.com`.

**Pull request merged**
