### PR TITLE
New post: lvgl speaks Hebrew

### PR DESCRIPTION
**Pull request by amirgon**

### CODE REVIEW

**Comment by kisvegabor** [comment]
That's great! Let me know if I can merge it!

**Comment by amirgon** [comment]
> That's great! Let me know if I can merge it!

You can merge it - just take a look if I missed anything, or any typos.
Feel free to add anything you think is relevant.

**Comment by kisvegabor** [comment]
> Feel free to add anything you think is relevant.

Then if you don't mind, I'll add a short C example too.


Can you add a link to the simulator with your example?

**Comment by amirgon** [comment]
Unfortunately, since fonts cannot be loaded on runtime, the online
simulator doesn't support Hebrew fonts.

**Comment by embeddedt** [comment]
> Unfortunately, since fonts cannot be loaded on runtime, the online
simulator doesn't support Hebrew fonts.

Are you referring to the MicroPython simulator? I can build a Hebrew font into the new version if you want. Just let me know what needs to be changed.

**Comment by amirgon** [comment]
> Are you referring to the MicroPython simulator? I can build a Hebrew font into the new version if you want. Just let me know what needs to be changed.

@kisvegabor do you think it's worthwhile bringing up a special build of MicroPython simulator with Hebrew font support, only for adding a link to the simulator in the example? I'm not sure about that.

**Comment by kisvegabor** [comment]
> do you think it's worthwhile bringing up a special build of MicroPython simulator with Hebrew font support, only for adding a link to the simulator in the example? I'm not sure about that.

Actually I find it a good idea. We can add other fonts too, such as Chinese (or CJK in general). IMO it'd help people to share codes easier. We can document what addition fonts exists in the simulator. 
Or we can reconsider the built-in font of lvgl itself. Maybe a 16 px Hebrew, Cyrillic and CJK font can be added too as an example. What do you think?

**Comment by amirgon** [comment]
> What do you think?

Ok. 

@embeddedt were you able to build emscripten with up-to-date lv_bindings?  

If you did, all you need to do is add to `lv_conf.h`:
```c
#define LV_FONT_CUSTOM_DECLARE LV_FONT_DECLARE(lv_font_heb_16)
```
and link it with `lv_font_heb_16.c`

**Comment by embeddedt** [comment]
Yes. I will recompile with the Hebrew font within the next few days.

**Comment by kisvegabor** [comment]
@embeddedt 
Great, thank you!

**Comment by embeddedt** [comment]
@amirgon I've added the Hebrew font, but I had to make a local, untracked change to the `lv_conf.h` file within the `lv_bindings` repository. Can you add a flag to `lv_bindings` to enable that font and update the `master` branch of `lv_micropython` with that version of `lv_bindings`?

**Comment by embeddedt** [comment]
It should be visible on `sim.littlevgl.com` once GitHub picks up on the submodule update.

**Comment by amirgon** [comment]
> but I had to make a local, untracked change to the `lv_conf.h` file within the `lv_bindings` repository

No you don't have to.

That's why I've added `#ifndef` around many macros (recall I suggested adding this to the template).
All you have to do is build with make command line parameter (something like `make LV_CFLAGS="-DLV_FONT_CUSTOM_DECLARE=LV_FONT_DECLARE(lv_font_heb_16)"`

> It should be visible on `sim.littlevgl.com` once GitHub picks up on the submodule update.

Great!

**Comment by embeddedt** [comment]
> All you have to do is build with make command line parameter (something like `make LV_CFLAGS="-DLV_FONT_CUSTOM_DECLARE=LV_FONT_DECLARE(lv_font_heb_16)"`)

Thanks; I've rebuilt it this way and pushed the change.

**Comment by amirgon** [comment]
> Thanks; I've rebuilt it this way and pushed the change.

@embeddedt for some reason I don't see the Hebrew font in the simulator:
```python
import lvgl as lv
lv.init()

print("\n".join([x for x in dir(lv) if 'font' in x]))
```
prints:
```
font_get_bitmap_fmt_txt
font_get_glyph_bitmap
font_get_glyph_dsc
font_get_glyph_dsc_fmt_txt
font_get_glyph_width
font_get_line_height
font_glyph_dsc_t
font_roboto_16
font_roboto_28
font_t
```

I would expect to see `font_heb_16` there as well. When processing `lv_font.h` it [should have been treated](https://github.com/littlevgl/lvgl/blob/cdc2cf90ce66fc4f309ae7564f61fdce33dc7257/src/lv_font/lv_font.h#L155-L158) just like the roboto fonts.

Are you sure you've rebuilt it correctly?

(I'm not sure this is the problem, but you might need to set `LV_CFLAGS` [before including `py/py.mk`](https://github.com/littlevgl/lv_micropython/blob/de3d4f49ca4863d6b0a7d7568dc35d013e57450f/ports/javascript/Makefile#L14))

**Comment by embeddedt** [comment]
> (I'm not sure this is the problem, but you might need to set LV_CFLAGS before including py/py.mk)

Yes, that was the problem. I've rebuilt and pushed it (again!). Now I see `font_heb_16` appearing in that list.

**Comment by amirgon** [comment]
> Yes, that was the problem. I've rebuilt and pushed it (again!). Now I see `font_heb_16` appearing in that list.

@embeddedt Something is still wrong:
```python
import imp, sys
sys.path.append('https://raw.githubusercontent.com/littlevgl/lv_binding_micropython/master/lib')

import display_driver
```

Causes this error:
```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "imp.py", line 24, in importer
AttributeError: no such attribute
```

Looking at "imp.py", line 24:
```python
 print("INFO: getting online local version of", filen, file=sys.stderr)
```

Now try this:
```
>>> import sys
>>> sys.stderr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: no such attribute
```

**Where did stderr gone?**

(I'm not sure this is the problem, but you might want to enable `MICROPY_DEBUG_PRINTERS` on `javascript/mpconfigport.h`)

**Comment by embeddedt** [comment]
@amirgon Fixed.

**Comment by amirgon** [comment]
> @amirgon Fixed.

@embeddedt We should really have a CI. I find another issue every time I try it, sorry about that.

Now stdout is not working. Try `print('hello')` - nothing is printed.
I'm comparing `mpconfigport.h` with the unix port and maybe what's missing is
```c
#define MICROPY_DEBUG_PRINTER       (&mp_stderr_print)
#define MICROPY_ERROR_PRINTER       (&mp_stderr_print)
```

Again - just a guess.

**Comment by amirgon** [comment]
@kisvegabor / @embeddedt  - Is there a way, on runtime, to change all fonts? Or do I need to go element by element, style by style, and set the font to each?

**Comment by embeddedt** [comment]
@amirgon It turns out that stdio handling seems to have been broken for a while. It took me a while but it should be working now.

> Is there a way, on runtime, to change all fonts? Or do I need to go element by element, style by style, and set the font to each?

Right now, the only way to change fonts for all elements easily is to change the default font. As you know, in 7.0 we are planning to revamp the style system which should make this a lot easier.

**Comment by amirgon** [comment]
Ok. Thanks @embeddedt !

> Can you add a link to the simulator with your example?

@kisvegabor - Here it is:

https://sim.littlevgl.com/v6/micropython/ports/javascript/lvgl_editor.html?script_startup=https://gist.githubusercontent.com/amirgon/7bf15a66ba6d959bbf90d10f3da571be/raw/8684b5fa55318c184b1310663b187aaab5c65be6/init_lv_mp_js.py&script=https://gist.githubusercontent.com/amirgon/8526af6d09b4f07f784410c959647a33/raw/f29857159d0395efe2d11d2ecfccd18e015738f6/lvgl_heb_test1.py

**Comment by kisvegabor** [comment]
It's amazing! Will you add a link to the simulator with the example script?

I've added the C example and updated the date in the file name.

**Comment by amirgon** [comment]
> It's amazing! Will you add a link to the simulator with the example script?

Done.

**Comment by kisvegabor** [comment]
Merged, thank you!

**Pull request merged**
