### PR TITLE
MIPI display for LittlevGL

### PR DESCRIPTION
**Pull request by techtoys**

### CODE REVIEW

**Comment by techtoys** [comment]
This blog is about how to use a mipi display with LittlevGL

**Comment by kisvegabor** [comment]
Hi,

Thank you very much for this detailed guide.

I made some formatting on the post. If you are happy with them I'll merge it.

**Comment by techtoys** [comment]
Gabor, your formatting is good. I fixed the c array file not found problem too. I have forgot to include a component file in main directory and /lvgl too! Now is OK. Have uploaded the correct version just now.

Please merge it.

**Comment by kisvegabor** [comment]
Great! 

I forget one thing. Can you create a cover imaged in 300x300 px size? Without it, the LittelvGL logo will be displayed on the blogs home page. It can one of the photos too. The path to the cover photo should be set [here](https://github.com/littlevgl/blog/pull/3/files#diff-787e62d7e6e5ef67912ab82a1e008c09R5)

**Comment by kisvegabor** [comment]
@techtoys 
FYI, somebody is asking about your project on the Forum:
https://forum.littlevgl.com/viewtopic.php?f=7&t=21

**Comment by kisvegabor** [comment]
@techtoys 
Your post is on Hackaday: https://hackaday.com/2019/03/06/hacking-the-ipod-nano-display-beautiful/

Congratulations! :)

**Comment by techtoys** [comment]
Yes, didn't expect that. BTW, a non-stop R&D is going one here for another displays, a 1.3" round display for Smart watch, and a 5" mipi display combining with a BT815 GPU + ESP32 + SIM800 GMS modem for a smart phone. Of course, LittlevGL will be the GUI engine need less to say...

**Comment by kisvegabor** [comment]
Wow, sound very interesting! Can we expect a new blog post too? :)

**Comment by techtoys** [comment]
Definitely. Actually there is a program working with the same 1.54" mipi display by Arduino. Driven by SPI + LittlevGL of course. Wanted to write a blog but a second look to it, seems a lot repetitive. So I just put it aside and keep looking for something new, until I find a round display with touch panel that is stable in supply with decent quality. Will test it as soon as I can and work out something for a blog.

Regarding a smartphone actually I already have Arduino driving it with a 5" mipi display. CTP is also working. There remains to integrate LittlevGL to the GPU (BT815 of FTDIChip). Although this GPU has its own widgets but its syntax is native to itself. So I hope GPU is well supported with LittlevGL.

If you don't mind I would like to ask 2 questions here, one non-technical and the other a technical one.

(1) Technical: do you have any idea or recommendation for the message scheme that I could use it with LittlevGL? To be more specific, lets consider a smart phone. If we want to turn on and off the Wifi, there is a button with an icon work as a toggle switch. The GUI can be finished with LittlevGL. In a smart phone there is Android which the message system is well defined. However, for bare metal with our own graphical framework, it is better to set a message structure for tasks to pass between modules. From GUI to set Wifi on/off, vibrator on/off etc. Do you have any recommendation for such message scheme that works with LittlevGL?

(2) This is non-technical and personal as well. From the weight of your work which requires at least few hours per day, it seems impossible without any financial backup. Do you have any silicon vendor behind you to back up your job?

John

**Comment by kisvegabor** [comment]
> Will test it as soon as I can and work out something for a blog.

Great! :)

> Technical: do you have any idea or recommendation for the message scheme  ...

Usually, I create a `gui` folder for (including lvgl) and a `drv` folder. The driver has a well defined API and I use this API in PC simulator and real hardware project too. On the PC simulator, the drivers are mainly filled with `printf's`. I have functions like:
- audio_volume_up()
- wifi_get_ssids
- wifi_connect
- wifi_read
- etc.

> This is non-technical and personal as well.  ...

I have a normal 8-hours-per-day job and I do LittlevGL in my free time. So I don't have any extra financial background. However, I see that it won't work in the long term. As LittlevGL become more popular more and more questions and suggestions arrive and I feel that I'm already near to my limits. :) 
So a company background with a support team or some financial support would be awesome. This way LittlevGL could be taken more seriously. Now it still looks like a  "hobby" project without any warranties.  With a company, you could be sure that it's really something which won't end tomorrow.

**Comment by kisvegabor** [comment]
@techtoys 
I opened a dedicated forum for this post: https://forum.littlevgl.com/viewforum.php?f=14

There is a "Subscribe to this Forum" button at bottom of the page. When subscribed you will be notified if someone opens a new topic.

**Pull request closed without merging**
