### PR TITLE
PikaScript and lvgl: Make Python Lighter, Easier and Smarter

### PR DESCRIPTION
**Pull request by pikasTech**
An article about PikaScript and Python programming, PikaScript provides a new Python binding for lvgl that drastically reduces resource usage, is compatible with more IDEs, and provides better intelligent hints.

I'm having some problems building the documentation, but at least in markdown it looks normal, so please check it out, thanks.

```
bundle exec jekyll build
Traceback (most recent call last):
        20: from /usr/local/bin/jekyll:23:in `<main>'
        19: from /usr/lib/ruby/2.7.0/rubygems.rb:295:in `activate_bin_path'
        18: from /usr/lib/ruby/2.7.0/rubygems.rb:295:in `synchronize'
        17: from /usr/lib/ruby/2.7.0/rubygems.rb:297:in `block in activate_bin_path'
        16: from /usr/lib/ruby/2.7.0/rubygems.rb:234:in `finish_resolve'
        15: from /usr/lib/ruby/2.7.0/rubygems/request_set.rb:435:in `resolve_current'
        14: from /usr/lib/ruby/2.7.0/rubygems/request_set.rb:423:in `resolve'
        13: from /usr/lib/ruby/2.7.0/rubygems/resolver.rb:192:in `resolve'
        12: from /usr/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
        11: from /usr/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:64:in `resolve'
        10: from /usr/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:106:in `start_resolution'
         9: from /usr/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:165:in `initial_state'
         8: from /usr/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
         7: from /usr/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
         6: from /usr/lib/ruby/2.7.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
         5: from /usr/lib/ruby/2.7.0/rubygems/resolver.rb:279:in `sort_dependencies'
         4: from /usr/lib/ruby/2.7.0/rubygems/resolver.rb:279:in `with_index'
         3: from /usr/lib/ruby/2.7.0/rubygems/resolver.rb:279:in `sort_by'
         2: from /usr/lib/ruby/2.7.0/rubygems/resolver.rb:279:in `each'
         1: from /usr/lib/ruby/2.7.0/rubygems/resolver.rb:285:in `block in sort_dependencies'
/usr/lib/ruby/2.7.0/rubygems/resolver.rb:235:in `search_for': Unable to resolve dependency: user requested 'did_you_mean (= 1.4.0)' (Gem::UnsatisfiableDependencyError)
```

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]

**Comment by embeddedt** [comment]
This looks very interesting!

**Comment by pikasTech** [comment]
> 

Thanks!

**Comment by kisvegabor** [comment]
Wow, it's really interesting!

Recently I also had trouble with setting up jekyll and I've lost in the dependency hell...

Anyway, your post look great, so if you say it's read merge, I can merge it. 

BTW, we have page for Micropython in our [docs](https://docs.lvgl.io/master/get-started/bindings/micropython.html). What do you think,  would it be worth to add a site there too? 
 
EDIT: I've just noticed that you have already sent a [PR](https://github.com/lvgl/lvgl/pull/3615) for the docs too  :slightly_smiling_face:

**Comment by pikasTech** [comment]
> Wow, it's really interesting!
> 
> Recently I also had trouble with setting up jekyll and I've lost in the dependency hell...
> 
> Anyway, your post look great, so if you say it's read merge, I can merge it.
> 
> BTW, we have page for Micropython in our [docs](https://docs.lvgl.io/master/get-started/bindings/micropython.html). What do you think, would it be worth to add a site there too?
> 
> EDIT: I've just noticed that you have already sent a [PR](https://github.com/lvgl/lvgl/pull/3615) for the docs too 🙂

Thanks！ I am ready!

**Pull request merged**
